from gcp_video_analysis import VideoAnalysis

url_list = ["https://www.youtube.com/watch?v=EobxUa06Cnc",
            "https://www.youtube.com/watch?v=yMabKBVyXGQ",
            "https://www.youtube.com/watch?v=arT9vNIebQo",
            "https://www.youtube.com/watch?v=Yb8XUhxZeb8",
            "https://www.youtube.com/watch?v=z7HuA8qWlF0",
            "https://www.youtube.com/watch?v=rIL1Pz_Gm3c",
            "https://www.youtube.com/watch?v=cuhrjzKKncQ",
            "https://www.youtube.com/watch?v=Qfjf7zxc3VY",
            "https://www.youtube.com/watch?v=58d2fQWWCZY",
            "https://www.youtube.com/watch?v=nJX4llWUVfQ",
            "https://www.youtube.com/watch?v=05LYM3WMcNE",
            "https://www.youtube.com/watch?v=Ls22KPhLEFw",
            "https://www.youtube.com/watch?v=WV6Ug8776sA",
            "https://www.youtube.com/watch?v=jiEVuF8Y7nw",
            "https://www.youtube.com/watch?v=MRzeLDkWT1c&t=9s",
            "https://www.youtube.com/watch?v=G9KDqfpCgws&t=11s",
            "https://www.youtube.com/watch?v=UBVc3VvXw-A",
            "https://www.youtube.com/watch?v=bqHNxfarW6E&t=7s",
            "https://www.youtube.com/watch?v=h_fUIW7G1IM",
            "https://www.youtube.com/watch?v=Mh-x8kbJT5k&t=9s",
            "https://www.youtube.com/watch?v=eYmkY4wkOqQ",
            "https://www.youtube.com/watch?v=A9VEIsMyA1I",
            "https://www.youtube.com/watch?v=32d9JN4HvaM",
            "https://www.youtube.com/watch?v=ctHfSC7-4XA",
            "https://www.youtube.com/watch?v=veCJCJmqFlk",
            "https://www.youtube.com/watch?v=sBBmSjyCDxk",
            "https://www.youtube.com/watch?v=2sQMvexJuzM",
            "https://www.youtube.com/watch?v=TOuF7ZbcCUs&t=2s",
            "https://www.youtube.com/watch?v=ZyfxRR8SayQ",
            "https://www.youtube.com/watch?v=xlUVr3rJ59A",
            "https://www.youtube.com/watch?v=SQbGOBbIZLE",
            "https://www.youtube.com/watch?v=VMBYm0vFL8U",
            "https://www.youtube.com/watch?v=_v73NRZks6s",
            "https://www.youtube.com/watch?v=SOlqhfP6_kU&t=8s",
            "https://www.youtube.com/watch?v=F8VecNSi6HE"]

title_list = ["GoPro: Onboard the Fastest Hydroplanes with HyperSmooth 2.0",
              "GoPro: HERO7 Black #Hypersmooth - Brendan Fairclough’s Run at Red Bull Rampage 2018 in 4K",
              "GoPro: HERO7 Black #HyperSmooth - Whistler MTB in 4K",
              "GoPro: Urban Downhill MTB with #HyperSmooth | Jackson Goldstone",
              "GoPro: HERO7 Black #HyperSmooth - Dancing with Derek Hough in 4K",
              "GoPro: HERO7 Black #HyperSmooth - Dan Atherton Wales Downhill MTB in 4K",
              "GoPro: HERO7 Black #Hypersmooth - Ken Block at Sand Hollow in 4K",
              "GoPro: Florida Moto with Kailub Russell in 4K | HERO7 Black",
              "GoPro: HERO7 Black #HyperSmooth - Jeb Corliss Wingsuit Death Star Run in 4K",
              "GoPro: This is Action. This is HyperSmooth. This is HERO7 Black.",
              "GoPro: The Atherton's MTB in 4K | HERO7 Black",
              "GoPro: HERO7 Black #HyperSmooth - Sam Pilgrim's Stairs",
              "GoPro: HERO7 Black #Hypersmooth - Eagle Cam in 4K",
              "GoPro: HERO7 Black #HyperSmooth - Formula Drift 4K Race Drone",
              "GoPro: Kilian Jornet - Running Ridges",
              "GoPro: Introducing HERO7 Black in 4K - Shaky Video is Dead",
              "GoPro: HERO7 Black #Hypersmooth - B.C. Heli in 4K",
              "GoPro: Darkfest MTB Highlight 2019",
              "GoPro: Rafting the North Fork Payette River in 4K | HERO7 Black",
              "GoPro: Introducing HERO8 Black — Beyond Next Level",
              "GoPro: Travel and Skate Through Greece | HERO7 Black",
              "GoPro: Jackson Goldstone Urban Downhill | Welcome to the Team",
              "GoPro: Ken Block Utah Off-Road in 4K | HERO7 Black",
              "GoPro: Formula Drift with HERO7 Black FPV",
              "GoPro: Sam Pilgrim's Urban DH MTB | Down Puerto Vallarta",
              "GoPro: Andy McMillan - Welcome to the Team",
              "GoPro: Motocross Track Day with Tony Cairoli",
              "GoPro: This is HERO8 Black + MAX",
              "GoPro: Markus Eder's Insane Line | Kicking Horse Golden BC FWT19",
              "GoPro Snow: Travis Rice's Insane Pillow Line",
              "GoPro Snow: Powder Vibes in Austria",
              "GoPro: MTB Downhill Challenge Medellín with Sam Pilgrim and Nicholi Rogatkin",
              "GoPro: Darkfest MTB Course Preview 2019",
              "GoPro Awards: Surfing Storm Swells",
              "GoPro: Kilian Bron's Winning Run at Mountain of Hell"]


VA = VideoAnalysis()

for url, title in zip(url_list, title_list):
    file_dir, file_name = VA.download_video(url, title)
    VA.analyze_video(file_dir, file_name)
